version: "3.7"

services:
  # app:
  #   build: .
  #   env_file: auth.env
  #   volumes:
  #     - .:/usr/src/themoviepredictor
  #   networks:
  #     - database_net
  #   command: tail -f /dev/null
  #   depends_on:
  #     - database
  database:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=predictor
      - MYSQL_PASSWORD=predictor
      - MYSQL_DATABASE=predictor
    networks:
      - database_net
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default_authentication_plugin=mysql_native_password
  adminer:
    image: dehy/adminer
    networks:
      - database_net
    ports:
      - 8080:80

networks:
  database_net:
    driver: bridge

volumes:
  database_data:
